project:
  type: book

book:
  title: "SUMO Tutorial"
  author: "유윤임"
  site-url : https://doripopo.github.io/sumo_tutorial_book/
  description: "교통 시뮬레이션 SUMO 설치, vscode 설치 등의 환경 설정, 네트워크 생성, 통행 생성,시뮬레이션 실행, Openstreet map import를 다루는 한국어 튜토리얼"
  date: "10/4/2026"
  chapters:
    - index.qmd
    - intro.qmd
    - part : install.qmd
      chapters:
        - install_vscode_in_window.qmd
        - install_python_in_window.qmd
        - install_sumo_in_window.qmd
        - SUMO mac OS building.qmd

    - part : basic_example.qmd
      chapters:
        - basic_net_generate.qmd 
        - basic_net_traffic_sign.qmd 
        - basic_trip_generate.qmd 
        - basic_simulation.qmd
        - basic_output.qmd
    - openstreet_map_import.qmd
    - summary.qmd
    - asked.qmd
    - self_study.qmd
    - qna_method.qmd


bibliography: references.bib

resources: 
  - robots.txt
  - video/*
  - image/*

website:
  open-graph: true
  twitter-card: true

format:
  html:
    theme:
      - cosmo
      - brand
  # pdf:
  #   documentclass: scrreprt



