project:
  type: book

book:
  title: "SUMO Tutorial"
  author: "유윤임"
  date: "10/4/2026"
  chapters:
    - index.qmd
    - intro.qmd
    - part : install.qmd
      chapters:
        - install_vscode_in_window.qmd
        - install_python_in_window.qmd
        - install_sumo_in_window.qmd
        - SUMO mac OS building.qmd

    - part : basic_example.qmd
      chapters:
        - basic_net_generate.qmd 
        - basic_net_traffic_sign.qmd 
        - basic_trip_generate.qmd 
        - basic_simulation.qmd
        - basic_output.qmd
    - openstreet_map_import.qmd
    - summary.qmd
    - asked.qmd
    - self_study.qmd
    - qna_method.qmd


bibliography: references.bib

resources: 
  - video/*
  - image/*

format:
  html:
    theme:
      - cosmo
      - brand
  pdf:
    documentclass: scrreprt



