# 결과 파일 해석

## edge_output.xml Parameter 설명

- travelTime : 평균 구간속도 기준 edge, lane 구간을 통과하는데 걸리는 시간(초)
- watingTime: lane에서 달리지 못하고 대기하는 자동차의 대기 시간의 총합(대기시간)
	- ==watingTime이 직관적으로 이해하기 쉽다==
- timeLoss: desired 속도보다 느리게 달려서 잃게 되는 시간의 총합
	- desired의 결정방식


### edge based

| Name              | Type                 | Description                                                                                                                                                                                                                                                                                                                          |
| ----------------- | -------------------- | ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------ |
| begin             | (simulation) seconds | The first time step the values were collected in                                                                                                                                                                                                                                                                                     |
| end               | (simulation) seconds | The last time step + DELTA_T in which the reported values were collected                                                                                                                                                                                                                                                             |
| edge@id           | (edge) id            | The name of the reported edge                                                                                                                                                                                                                                                                                                        |
| lane@id           | (lane) id            | The name of the reported lane                                                                                                                                                                                                                                                                                                        |
| sampledSeconds    | s                    | The number of vehicles that are present on the edge/lane in each second summed up over the measurement interval (may be subseconds if a vehicle enters/leaves the edge/lane).                                                                                                                                                        |
| traveltime        | s                    | Time needed to pass the edge/lane, note that this is just an estimation based on the mean speed, not the exact time the vehicles needed. The value is based on the time needed for the front of the vehicle to pass the edge.                                                                                                        |
| overlapTraveltime | s                    | Time needed to pass the edge/lane completely, note that this is just an estimation based on the mean speed, not the exact time the vehicles needed. The value is based on the time any part of the vehicle was the edge.                                                                                                             |
| density           | #veh/km              | Vehicle density on the edge                                                                                                                                                                                                                                                                                                          |
| overlapDensity    | #veh/km              | Vehicle density on the edge. This value counts vehicles if any part along it's length touches the edge. This should not be used for flow computation                                                                                                                                                                                 |
| laneDensity       | #veh/km/lane         | Vehicle density on the edge per lane                                                                                                                                                                                                                                                                                                 |
| occupancy         | %                    | Occupancy of the edge/lane in %. A value of 100 would indicate vehicles standing bumper to bumper on the whole edge (minGap=0).                                                                                                                                                                                                      |
| waitingTime       | s                    | The total number of seconds vehicles were considered halting (speed < speedThreshold). Summed up over all vehicles                                                                                                                                                                                                                   |
| timeLoss          | s                    | The total number of seconds vehicles lost due to driving slower than desired (summed up over all vehicles)                                                                                                                                                                                                                           |
| speed             | m/s                  | The mean speed on the edge/lane within the reported interval.  <br>  <br>**Caution:** This is an average over time and space (space-mean-speed), rather than a local average over the vehicles (time-mean-speed). Since slow vehicles spend more time on the edge they will have a proportionally bigger influence on average speed. |
| speedRelative     | -                    | quotient of mean speed value (see above) and the lane speed limit                                                                                                                                                                                                                                                                    |
| departed          | #veh                 | The number of vehicles that have been emitted onto the edge/lane within the described interval                                                                                                                                                                                                                                       |
| arrived           | #veh                 | The number of vehicles that have finished their route on the edge lane                                                                                                                                                                                                                                                               |
| entered           | #veh                 | The number of vehicles that have entered the edge/lane by moving from upstream                                                                                                                                                                                                                                                       |
| left              | #veh                 | The number of vehicles that have left the edge/lane by moving downstream                                                                                                                                                                                                                                                             |
| laneChangedFrom   | #veh                 | The number of vehicles that changed away from this lane                                                                                                                                                                                                                                                                              |
| laneChangedTo     | #veh                 | The number of vehicles that changed to this lane                                                                                                                                                                                                                                                                                     |
| vaporized         | #veh                 | The number of vehicles vaporized on this edge **(only present if #veh > 0)**                                                                                                                                                                                                                                                         |
| teleported        | #veh                 | The number of vehicles teleported from this edge **(only present if #veh > 0)**                                                                                                                                                                                                                                                      |
| flow              | #veh/hour            | The number of vehicles passing this edge per hour. Vehicles that depart on this edge beyond position 0 or arrive before the end of the edge are fractionally disocunted                                                                                                                                                              |

| Attribute Name      | Value Type                               | Description                                                                                                                                                                                                                                                                                                                                    |
| ------------------- | ---------------------------------------- | ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- |
| **id**              | id (string)                              | The id of this set of measurements. This user-defined id is needed for differentiating between multiple sets of measurements in a single output file.                                                                                                                                                                                          |
| **file**            | filename                                 | The path to the output file. The path may be relative.                                                                                                                                                                                                                                                                                         |
| period (alias freq) | int (time)                               | The aggregation period the values the detector collects shall be summed up. If not given the whole time interval from begin to end (see below) is aggregated.                                                                                                                                                                                  |
| begin               | int (time)                               | The time to start writing (intervals starting before this time are discarded). If not given, the simulation's begin is used.                                                                                                                                                                                                                   |
| end                 | int (time)                               | The time to end writing (intervals starting at or after this time are discarded). If not given the simulation's end is used.                                                                                                                                                                                                                   |
| excludeEmpty        | string (true, false, defaults, modified) | If set to true, edges/lanes which were not used by a vehicle during this period will not be written; _default: false_. If set to "defaults" default values for travel time and speed depending on edge length and maximum speed get printed, "modified" will print values only for empty edges which have a dynamically adapted maximum speed. |
| withInternal        | bool                                     | If set, junction internal edges/lanes will be written as well; _default: false_.                                                                                                                                                                                                                                                               |
| maxTraveltime       | float (time)                             | The maximum traveltime in seconds to write if only very small movements occur; _default 100000_.                                                                                                                                                                                                                                               |
| minSamples          | float (time)                             | The minimum total number of seconds vehicles have to be on the edge / lane to consider it non-empty; _default: >0_.                                                                                                                                                                                                                            |
| speedThreshold      | float (m/s)                              | The maximum speed to consider a vehicle halting; _default 0.1_.                                                                                                                                                                                                                                                                                |
| vTypes              | string                                   | space separated list of vehicle type ids to consider. If not given, all vTypes will be considered.                                                                                                                                                                                                                                             |
| trackVehicles       | bool                                     | whether aggregation should be performed over all vehicles that entered the edge/lane in the aggregation interval                                                                                                                                                                                                                               |
| detectPersons       | string list                              | whether pedestrians shall be recorded instead of vehicles. Allowed value is _walk_.  <br>**Note:** further modes are planned                                                                                                                                                                                                                   |
| writeAttributes     | string list                              | list of attribute names that shall be written (defaults to all attribute)                                                                                                                                                                                                                                                                      |
| edges               | string list                              | restrict output to the given list of edge ids                                                                                                                                                                                                                                                                                                  |
| edgesFile           | filename                                 | restrict output to the given the list of edges given in file (either one edgeID per line or an id prefixed with 'edge:' as in a [selection file](https://sumo.dlr.de/docs/Netedit/editModesCommon.html#selection_operations))                                                                                                                  |


# Reference

- [sumo document : Lane or Edge based traffic measures](https://sumo.dlr.de/docs/Simulation/Output/Lane-_or_Edge-based_Traffic_Measures.html)
- [sumo document : trip info](https://sumo.dlr.de/docs/Simulation/Output/TripInfo.html)

