# SUMO 환경 구성하기 {.unnumbered}

본 장에서 SUMO 환경을 구성하는 법을 아래와 같이 설명하였습니다.

1. vs code 설치
2. miniconda 설치와 sumo python 환경 설정
3. sumo 설치

본래, SUMO만 설치하여도 시뮬레이션을 할 수 있습니다. 다만, SUMO 프로그램은 Python tool set을 제공하고 있어, 이를 이용하기 위해서는 python이 필요합니다. 또한, SUMO의 입력과 출력 파일은 기본적으로 xml 형식으로 이루어져 있습니다. 이 xml 파일을 메모장으로 편집할 수 있지만, vscode와 같은 편집기를 사용하면 보다 쉽게 편집하고, 볼 수 있습니다. 미래에 sumo를 응용하여 쓰게 될 때, python code 작성하거나, sumo python tool 프로그램 사용할 때, vscode가 도움이 될 수 있습니다.

이에 vscode 설치 방법, miniconda 설치 방법을 함께 서술하였습니다. sumo만 필요한 경우, sumo 설치만 따라하셔도 괜찮습니다. 그리고 기존에 사용하시는 코드 편집기가 이미 존재하고, python도 설치되어 있다면, 해당 장을 생략하셔도 괜찮습니다. 

설치 방법을 간략하게 작성하였는데, 보다 상세한 가이드라인이 필요한 경우, 구글 검색창에 `윈도우 vscdoe 설치`와 같이 입력하시면 상세한 자료를 찾을 수 있습니다.


순수 python의 경우, 버전관리, 앞으로 설치할 python, 환경변수 설정 등이 복잡한 부분이 있어 miniconda를 설치하는 것으로 안내드립니다. miniconda는 가상 환경을 만들어, python을 이용할 수 있어 파이썬 버전관리, python path 관리 등의 문제를 덜 겪을 수 있습니다.

이와 별개로, 순수 python이 이미 설치되어 있고, python path가 설정되어 있다면, 이 miniconda를 설치하지 않으셔도 됩니다. 본 튜토리얼에서 sumo conda 환경을 활성화하는 부분을 빼고 python을 사용하는 부분을 따라하시면 되기 때문입니다.


